services:
  - type: web
    name: whatsapp-ae-bot
    env: node
    plan: starter
    buildCommand: "npm install"
    startCommand: "node bot.js"
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
    disk:
      name: auth-storage
      mountPath: /app/.wwebjs_auth
      sizeGB: 1
